#ifndef __SYSCALL_LIST_RISCV__
#define __SYSCALL_LIST_RISCV__		1

#define __NR_read 0
#define __NR_write 1
#define __NR_open 2
#define __NR_close 3
#define __NR_stat 4
#define __NR_fstat 5
#define __NR_lstat 6
#define __NR_poll 7
#define __NR_lseek 8
#define __NR_brk 9
#define __NR_nanosleep 10
#define __NR_getpid 11
#define __NR_fork 12
#define __NR_vfork 13
#define __NR_execve 14
#define __NR_exit 15
#define __NR_wait4 16
#define __NR_kill 17
#define __NR_uname 18
#define __NR_getcwd 19
#define __NR_chdir 20
#define __NR_fchdir 21
#define __NR_rename 22
#define __NR_mkdir 23
#define __NR_rmdir 24
#define __NR_creat 25
#define __NR_chmod 26
#define __NR_fchmod 27
#define __NR_chown 28
#define __NR_fchown 29
#define __NR_lchown 30


#define SYS_read  __NR_read
#define SYS_write  __NR_write
#define SYS_open  __NR_open
#define SYS_close  __NR_close
#define SYS_stat  __NR_stat
#define SYS_fstat  __NR_fstat
#define SYS_lstat  __NR_lstat
#define SYS_poll  __NR_poll
#define SYS_lseek  __NR_lseek
#define SYS_brk  __NR_brk
#define SYS_pipe  __NR_pipe
#define SYS_nanosleep  __NR_nanosleep
#define SYS_getpid  __NR_getpid
#define SYS_socket  __NR_socket
#define SYS_clone  __NR_clone
#define SYS_fork  __NR_fork
#define SYS_vfork  __NR_vfork
#define SYS_execve  __NR_execve
#define SYS_exit  __NR_exit
#define SYS_wait4  __NR_wait4
#define SYS_kill  __NR_kill
#define SYS_uname  __NR_uname
#define SYS_semget  __NR_semget
#define SYS_semop  __NR_semop
#define SYS_getcwd  __NR_getcwd
#define SYS_chdir  __NR_chdir
#define SYS_fchdir  __NR_fchdir
#define SYS_rename  __NR_rename
#define SYS_mkdir  __NR_mkdir
#define SYS_rmdir  __NR_rmdir
#define SYS_creat  __NR_creat
#define SYS_chmod  __NR_chmod
#define SYS_fchmod  __NR_fchmod
#define SYS_chown  __NR_chown
#define SYS_fchown  __NR_fchown
#define SYS_lchown  __NR_lchown

#endif
